<?php
require_once("checkLogin.php");
?>
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.1.0/mdb.min.css" rel="stylesheet"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <style>@import url("https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css");</style>
    <style>
                /* Absolute Center Spinner */
        .loading {
        position: fixed;
        z-index: 999;
        height: 2em;
        width: 2em;
        overflow: show;
        margin: auto;
        top: 0;
        left: 0;
        bottom: 0;
        right: 0;
        }

        /* Transparent Overlay */
        .loading:before {
        content: '';
        display: block;
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
            background: radial-gradient(rgba(20, 20, 20,.8), rgba(0, 0, 0, .8));

        background: -webkit-radial-gradient(rgba(20, 20, 20,.8), rgba(0, 0, 0,.8));
        }

        /* :not(:required) hides these rules from IE9 and below */
        .loading:not(:required) {
        /* hide "loading..." text */
        font: 0/0 a;
        color: transparent;
        text-shadow: none;
        background-color: transparent;
        border: 0;
        }

        .loading:not(:required):after {
        content: '';
        display: block;
        font-size: 10px;
        width: 1em;
        height: 1em;
        margin-top: -0.5em;
        -webkit-animation: spinner 150ms infinite linear;
        -moz-animation: spinner 150ms infinite linear;
        -ms-animation: spinner 150ms infinite linear;
        -o-animation: spinner 150ms infinite linear;
        animation: spinner 150ms infinite linear;
        border-radius: 0.5em;
        -webkit-box-shadow: rgba(255,255,255, 0.75) 1.5em 0 0 0, rgba(255,255,255, 0.75) 1.1em 1.1em 0 0, rgba(255,255,255, 0.75) 0 1.5em 0 0, rgba(255,255,255, 0.75) -1.1em 1.1em 0 0, rgba(255,255,255, 0.75) -1.5em 0 0 0, rgba(255,255,255, 0.75) -1.1em -1.1em 0 0, rgba(255,255,255, 0.75) 0 -1.5em 0 0, rgba(255,255,255, 0.75) 1.1em -1.1em 0 0;
        box-shadow: rgba(255,255,255, 0.75) 1.5em 0 0 0, rgba(255,255,255, 0.75) 1.1em 1.1em 0 0, rgba(255,255,255, 0.75) 0 1.5em 0 0, rgba(255,255,255, 0.75) -1.1em 1.1em 0 0, rgba(255,255,255, 0.75) -1.5em 0 0 0, rgba(255,255,255, 0.75) -1.1em -1.1em 0 0, rgba(255,255,255, 0.75) 0 -1.5em 0 0, rgba(255,255,255, 0.75) 1.1em -1.1em 0 0;
        }

        /* Animation */

        @-webkit-keyframes spinner {
        0% {
            -webkit-transform: rotate(0deg);
            -moz-transform: rotate(0deg);
            -ms-transform: rotate(0deg);
            -o-transform: rotate(0deg);
            transform: rotate(0deg);
        }
        100% {
            -webkit-transform: rotate(360deg);
            -moz-transform: rotate(360deg);
            -ms-transform: rotate(360deg);
            -o-transform: rotate(360deg);
            transform: rotate(360deg);
        }
        }
        @-moz-keyframes spinner {
        0% {
            -webkit-transform: rotate(0deg);
            -moz-transform: rotate(0deg);
            -ms-transform: rotate(0deg);
            -o-transform: rotate(0deg);
            transform: rotate(0deg);
        }
        100% {
            -webkit-transform: rotate(360deg);
            -moz-transform: rotate(360deg);
            -ms-transform: rotate(360deg);
            -o-transform: rotate(360deg);
            transform: rotate(360deg);
        }
        }
        @-o-keyframes spinner {
        0% {
            -webkit-transform: rotate(0deg);
            -moz-transform: rotate(0deg);
            -ms-transform: rotate(0deg);
            -o-transform: rotate(0deg);
            transform: rotate(0deg);
        }
        100% {
            -webkit-transform: rotate(360deg);
            -moz-transform: rotate(360deg);
            -ms-transform: rotate(360deg);
            -o-transform: rotate(360deg);
            transform: rotate(360deg);
        }
        }
        @keyframes spinner {
        0% {
            -webkit-transform: rotate(0deg);
            -moz-transform: rotate(0deg);
            -ms-transform: rotate(0deg);
            -o-transform: rotate(0deg);
            transform: rotate(0deg);
        }
        100% {
            -webkit-transform: rotate(360deg);
            -moz-transform: rotate(360deg);
            -ms-transform: rotate(360deg);
            -o-transform: rotate(360deg);
            transform: rotate(360deg);
        }
        }
    </style>
    <style>
        * {
        box-sizing: border-box;
        }

        body {
        font: 16px Arial;  
        }

        /*the container must be positioned relative:*/
        .autocomplete {
        position: relative;
        display: inline-block;
        }

        input {
        border: 1px solid transparent;
        background-color: #f1f1f1;
        padding: 10px;
        font-size: 16px;
        }

        input[type=text] {
        background-color: #f1f1f1;
        width: 100%;
        }

        input[type=submit] {
        background-color: DodgerBlue;
        color: #fff;
        cursor: pointer;
        }

        .autocomplete-items {
        position: absolute;
        border: 1px solid #d4d4d4;
        border-bottom: none;
        border-top: none;
        z-index: 99;
        /*position the autocomplete items to be the same width as the container:*/
        top: 100%;
        left: 0;
        right: 0;
        }

        .autocomplete-items div {
        padding: 10px;
        cursor: pointer;
        background-color: #fff; 
        border-bottom: 1px solid #d4d4d4; 
        }

        /*when hovering an item:*/
        .autocomplete-items div:hover {
        background-color: #e9e9e9; 
        }

        /*when navigating through the items using the arrow keys:*/
        .autocomplete-active {
        background-color: DodgerBlue !important; 
        color: #ffffff; 
        }
    </style>
  </head>
  <body class="p-4 m-auto" style="max-width: 500px; min-height: 100vh; border-left: 3px solid gray; border-right: 3px solid gray;" id="demo">
    <form id="form-utf" action="javascript:void(0);" onsubmit="submitme()" method="POST" autocomplete="off">
        <div class="row p-0 m-0">
            <label for=""><h2><b>Server Name</b></h2></label>
            <div class="autocomplete">
            <input type="text" id="myInput" class="form-control rounded-pill p-3 mt-2" name="myCountry" placeholder="Server Name" required>
            </div>
            <button type="submit" class="rounded-pill p-4 mt-5 btn btn-dark m-auto" style="width: 90%;">Create Server</button>
        </div>
    </form>
    <br><br><br>
    <div class="loading" id="loading" style="display: none;">Loading&#8230;</div>
    <div class="content"><h3></h3></div>
    <script>
        function submitme(){
            document.getElementById('loading').style.display = 'block';
            let data = $('#form-utf').serialize();
            const xhttp = new XMLHttpRequest();
            xhttp.onload = function() {
                document.getElementById("demo").innerHTML = this.responseText;
                }
            xhttp.open("POST", "createServerbackend.php");
            xhttp.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
            xhttp.send(data);
        }
    </script>
    <script>
function autocomplete(inp, arr) {
  /*the autocomplete function takes two arguments,
  the text field element and an array of possible autocompleted values:*/
  var currentFocus;
  /*execute a function when someone writes in the text field:*/
  inp.addEventListener("input", function(e) {
      var a, b, i, val = this.value;
      /*close any already open lists of autocompleted values*/
      closeAllLists();
      if (!val) { return false;}
      currentFocus = -1;
      /*create a DIV element that will contain the items (values):*/
      a = document.createElement("DIV");
      a.setAttribute("id", this.id + "autocomplete-list");
      a.setAttribute("class", "autocomplete-items");
      /*append the DIV element as a child of the autocomplete container:*/
      this.parentNode.appendChild(a);
      /*for each item in the array...*/
      for (i = 0; i < arr.length; i++) {
        /*check if the item starts with the same letters as the text field value:*/
        if (arr[i].substr(0, val.length).toUpperCase() == val.toUpperCase()) {
          /*create a DIV element for each matching element:*/
          b = document.createElement("DIV");
          /*make the matching letters bold:*/
          b.innerHTML = "<strong>" + arr[i].substr(0, val.length) + "</strong>";
          b.innerHTML += arr[i].substr(val.length);
          /*insert a input field that will hold the current array item's value:*/
          b.innerHTML += "<input type='hidden' value='" + arr[i] + "'>";
          /*execute a function when someone clicks on the item value (DIV element):*/
          b.addEventListener("click", function(e) {
              /*insert the value for the autocomplete text field:*/
              inp.value = this.getElementsByTagName("input")[0].value;
              /*close the list of autocompleted values,
              (or any other open lists of autocompleted values:*/
              closeAllLists();
          });
          a.appendChild(b);
        }
      }
  });
  /*execute a function presses a key on the keyboard:*/
  inp.addEventListener("keydown", function(e) {
      var x = document.getElementById(this.id + "autocomplete-list");
      if (x) x = x.getElementsByTagName("div");
      if (e.keyCode == 40) {
        /*If the arrow DOWN key is pressed,
        increase the currentFocus variable:*/
        currentFocus++;
        /*and and make the current item more visible:*/
        addActive(x);
      } else if (e.keyCode == 38) { //up
        /*If the arrow UP key is pressed,
        decrease the currentFocus variable:*/
        currentFocus--;
        /*and and make the current item more visible:*/
        addActive(x);
      } else if (e.keyCode == 13) {
        /*If the ENTER key is pressed, prevent the form from being submitted,*/
        e.preventDefault();
        if (currentFocus > -1) {
          /*and simulate a click on the "active" item:*/
          if (x) x[currentFocus].click();
        }
      }
  });
  function addActive(x) {
    /*a function to classify an item as "active":*/
    if (!x) return false;
    /*start by removing the "active" class on all items:*/
    removeActive(x);
    if (currentFocus >= x.length) currentFocus = 0;
    if (currentFocus < 0) currentFocus = (x.length - 1);
    /*add class "autocomplete-active":*/
    x[currentFocus].classList.add("autocomplete-active");
  }
  function removeActive(x) {
    /*a function to remove the "active" class from all autocomplete items:*/
    for (var i = 0; i < x.length; i++) {
      x[i].classList.remove("autocomplete-active");
    }
  }
  function closeAllLists(elmnt) {
    /*close all autocomplete lists in the document,
    except the one passed as an argument:*/
    var x = document.getElementsByClassName("autocomplete-items");
    for (var i = 0; i < x.length; i++) {
      if (elmnt != x[i] && elmnt != inp) {
        x[i].parentNode.removeChild(x[i]);
      }
    }
  }
  /*execute a function when someone clicks in the document:*/
  document.addEventListener("click", function (e) {
      closeAllLists(e.target);
  });
}

/*An array containing all the country names in the world:*/
var countries = [
  "Mumbai",
  "Delhi",
  "Bengaluru",
  "Ahmedabad",
  "Hyderabad",
  "Chennai",
  "Kolkata",
  "Pune",
  "Jaipur",
  "Surat",
  "Lucknow",
  "Kanpur",
  "Nagpur",
  "Patna",
  "Indore",
  "Thane",
  "Bhopal",
  "Visakhapatnam",
  "Vadodara",
  "Firozabad",
  "Ludhiana",
  "Rajkot",
  "Agra",
  "Siliguri",
  "Nashik",
  "Faridabad",
  "Patiala",
  "Meerut",
  "Kalyan-Dombivali",
  "Vasai-Virar",
  "Varanasi",
  "Srinagar",
  "Dhanbad",
  "Jodhpur",
  "Amritsar",
  "Raipur",
  "Allahabad",
  "Coimbatore",
  "Jabalpur",
  "Gwalior",
  "Vijayawada",
  "Madurai",
  "Guwahati",
  "Chandigarh",
  "Hubli-Dharwad",
  "Amroha",
  "Moradabad",
  "Gurgaon",
  "Aligarh",
  "Solapur",
  "Ranchi",
  "Jalandhar",
  "Tiruchirappalli",
  "Bhubaneswar",
  "Salem",
  "Warangal",
  "Mira-Bhayandar",
  "Thiruvananthapuram",
  "Bhiwandi",
  "Saharanpur",
  "Guntur",
  "Amravati",
  "Bikaner",
  "Noida",
  "Jamshedpur",
  "Bhilai Nagar",
  "Cuttack",
  "Kochi",
  "Udaipur",
  "Bhavnagar",
  "Dehradun",
  "Asansol",
  "Nanded-Waghala",
  "Ajmer",
  "Jamnagar",
  "Ujjain",
  "Sangli",
  "Loni",
  "Jhansi",
  "Pondicherry",
  "Nellore",
  "Jammu",
  "Belagavi",
  "Raurkela",
  "Mangaluru",
  "Tirunelveli",
  "Malegaon",
  "Gaya",
  "Tiruppur",
  "Davanagere",
  "Kozhikode",
  "Akola",
  "Kurnool",
  "Bokaro Steel City",
  "Rajahmundry",
  "Ballari",
  "Agartala",
  "Bhagalpur",
  "Latur",
  "Dhule",
  "Korba",
  "Bhilwara",
  "Brahmapur",
  "Mysore",
  "Muzaffarpur",
  "Ahmednagar",
  "Kollam",
  "Raghunathganj",
  "Bilaspur",
  "Shahjahanpur",
  "Thrissur",
  "Alwar",
  "Kakinada",
  "Nizamabad",
  "Sagar",
  "Tumkur",
  "Hisar",
  "Rohtak",
  "Panipat",
  "Darbhanga",
  "Kharagpur",
  "Aizawl",
  "Ichalkaranji",
  "Tirupati",
  "Karnal",
  "Bathinda",
  "Rampur",
  "Shivamogga",
  "Ratlam",
  "Modinagar",
  "Durg",
  "Shillong",
  "Imphal",
  "Hapur",
  "Ranipet",
  "Anantapur",
  "Arrah",
  "Karimnagar",
  "Parbhani",
  "Etawah",
  "Bharatpur",
  "Begusarai",
  "New Delhi",
  "Chhapra",
  "Kadapa",
  "Ramagundam",
  "Pali",
  "Satna",
  "Vizianagaram",
  "Katihar",
  "Hardwar",
  "Sonipat",
  "Nagercoil",
  "Thanjavur",
  "Murwara (Katni)",
  "Naihati",
  "Sambhal",
  "Nadiad",
  "Yamunanagar",
  "English Bazar",
  "Eluru",
  "Munger",
  "Panchkula",
  "Raayachuru",
  "Panvel",
  "Deoghar",
  "Ongole",
  "Nandyal",
  "Morena",
  "Bhiwani",
  "Porbandar",
  "Palakkad",
  "Anand",
  "Purnia",
  "Baharampur",
  "Barmer",
  "Morvi",
  "Orai",
  "Bahraich",
  "Sikar",
  "Vellore",
  "Singrauli",
  "Khammam",
  "Mahesana",
  "Silchar",
  "Sambalpur",
  "Rewa",
  "Unnao",
  "Hugli-Chinsurah",
  "Raiganj",
  "Phusro",
  "Adityapur",
  "Alappuzha",
  "Bahadurgarh",
  "Machilipatnam",
  "Rae Bareli",
  "Jalpaiguri",
  "Bharuch",
  "Pathankot",
  "Hoshiarpur",
  "Baramula",
  "Adoni",
  "Jind",
  "Tonk",
  "Tenali",
  "Kancheepuram",
  "Vapi",
  "Sirsa",
  "Navsari",
  "Mahbubnagar",
  "Puri",
  "Robertson Pet",
  "Erode",
  "Batala",
  "Haldwani-cum-Kathgodam",
  "Vidisha",
  "Saharsa",
  "Thanesar",
  "Chittoor",
  "Veraval",
  "Lakhimpur",
  "Sitapur",
  "Hindupur",
  "Santipur",
  "Balurghat",
  "Ganjbasoda",
  "Moga",
  "Proddatur",
  "Srinagar",
  "Medinipur",
  "Habra",
  "Sasaram",
  "Hajipur",
  "Bhuj",
  "Shivpuri",
  "Ranaghat",
  "Shimla",
  "Tiruvannamalai",
  "Kaithal",
  "Rajnandgaon",
  "Godhra",
  "Hazaribag",
  "Bhimavaram",
  "Mandsaur",
  "Dibrugarh",
  "Kolar",
  "Bankura",
  "Mandya",
  "Dehri-on-Sone",
  "Madanapalle",
  "Malerkotla",
  "Lalitpur",
  "Bettiah",
  "Pollachi",
  "Khanna",
  "Neemuch",
  "Palwal",
  "Palanpur",
  "Guntakal",
  "Nabadwip",
  "Udupi",
  "Jagdalpur",
  "Motihari",
  "Pilibhit",
  "Dimapur",
  "Mohali",
  "Sadulpur",
  "Rajapalayam",
  "Dharmavaram",
  "Kashipur",
  "Sivakasi",
  "Darjiling",
  "Chikkamagaluru",
  "Gudivada",
  "Baleshwar Town",
  "Mancherial",
  "Srikakulam",
  "Adilabad",
  "Yavatmal",
  "Barnala",
  "Nagaon",
  "Narasaraopet",
  "Raigarh",
  "Roorkee",
  "Valsad",
  "Ambikapur",
  "Giridih",
  "Chandausi",
  "Purulia",
  "Patan",
  "Bagaha",
  "Hardoi ",
  "Achalpur",
  "Osmanabad",
  "Deesa",
  "Nandurbar",
  "Azamgarh",
  "Ramgarh",
  "Firozpur",
  "Baripada Town",
  "Karwar",
  "Siwan",
  "Rajampet",
  "Pudukkottai",
  "Anantnag",
  "Tadpatri",
  "Satara",
  "Bhadrak",
  "Kishanganj",
  "Suryapet",
  "Wardha",
  "Ranebennuru",
  "Amreli",
  "Neyveli (TS)",
  "Jamalpur",
  "Marmagao",
  "Udgir",
  "Tadepalligudem",
  "Nagapattinam",
  "Buxar",
  "Aurangabad",
  "Jehanabad",
  "Phagwara",
  "Khair",
  "Sawai Madhopur",
  "Kapurthala",
  "Chilakaluripet",
  "Aurangabad",
  "Malappuram",
  "Rewari",
  "Nagaur",
  "Sultanpur",
  "Nagda",
  "Port Blair",
  "Lakhisarai",
  "Panaji",
  "Tinsukia",
  "Itarsi",
  "Kohima",
  "Balangir",
  "Nawada",
  "Jharsuguda",
  "Jagtial",
  "Viluppuram",
  "Amalner",
  "Zirakpur",
  "Tanda",
  "Tiruchengode",
  "Nagina",
  "Yemmiganur",
  "Vaniyambadi",
  "Sarni",
  "Theni Allinagaram",
  "Margao",
  "Akot",
  "Sehore",
  "Mhow Cantonment",
  "Kot Kapura",
  "Makrana",
  "Pandharpur",
  "Miryalaguda",
  "Shamli",
  "Seoni",
  "Ranibennur",
  "Kadiri",
  "Shrirampur",
  "Rudrapur",
  "Parli",
  "Najibabad",
  "Nirmal",
  "Udhagamandalam",
  "Shikohabad",
  "Jhumri Tilaiya",
  "Aruppukkottai",
  "Ponnani",
  "Jamui",
  "Sitamarhi",
  "Chirala",
  "Anjar",
  "Karaikal",
  "Hansi",
  "Anakapalle",
  "Mahasamund",
  "Faridkot",
  "Saunda",
  "Dhoraji",
  "Paramakudi",
  "Balaghat",
  "Sujangarh",
  "Khambhat",
  "Muktsar",
  "Rajpura",
  "Kavali",
  "Dhamtari",
  "Ashok Nagar",
  "Sardarshahar",
  "Mahuva",
  "Bargarh",
  "Kamareddy",
  "Sahibganj",
  "Kothagudem",
  "Ramanagaram",
  "Gokak",
  "Tikamgarh",
  "Araria",
  "Rishikesh",
  "Shahdol",
  "Medininagar (Daltonganj)",
  "Arakkonam",
  "Washim",
  "Sangrur",
  "Bodhan",
  "Fazilka",
  "Palacole",
  "Keshod",
  "Sullurpeta",
  "Wadhwan",
  "Gurdaspur",
  "Vatakara",
  "Tura",
  "Narnaul",
  "Kharar",
  "Yadgir",
  "Ambejogai",
  "Ankleshwar",
  "Savarkundla",
  "Paradip",
  "Virudhachalam",
  "Kanhangad",
  "Kadi",
  "Srivilliputhur",
  "Gobindgarh",
  "Tindivanam",
  "Mansa",
  "Taliparamba",
  "Manmad",
  "Tanuku",
  "Rayachoti",
  "Virudhunagar",
  "Koyilandy",
  "Jorhat",
  "Karur",
  "Valparai",
  "Srikalahasti",
  "Neyyattinkara",
  "Bapatla",
  "Fatehabad",
  "Malout",
  "Sankarankovil",
  "Tenkasi",
  "Ratnagiri",
  "Rabkavi Banhatti",
  "Sikandrabad",
  "Chaibasa",
  "Chirmiri",
  "Palwancha",
  "Bhawanipatna",
  "Kayamkulam",
  "Pithampur",
  "Nabha",
  "Shahabad, Hardoi",
  "Dhenkanal",
  "Uran Islampur",
  "Gopalganj",
  "Bongaigaon City",
  "Palani",
  "Pusad",
  "Sopore",
  "Pilkhuwa",
  "Tarn Taran",
  "Renukoot",
  "Mandamarri",
  "Shahabad",
  "Barbil",
  "Koratla",
  "Madhubani",
  "Arambagh",
  "Gohana",
  "Ladnu",
  "Pattukkottai",
  "Sirsi",
  "Sircilla",
  "Tamluk",
  "Jagraon",
  "AlipurdUrban Agglomerationr",
  "Alirajpur",
  "Tandur",
  "Naidupet",
  "Tirupathur",
  "Tohana",
  "Ratangarh",
  "Dhubri",
  "Masaurhi",
  "Visnagar",
  "Vrindavan",
  "Nokha",
  "Nagari",
  "Narwana",
  "Ramanathapuram",
  "Ujhani",
  "Samastipur",
  "Laharpur",
  "Sangamner",
  "Nimbahera",
  "Siddipet",
  "Suri",
  "Diphu",
  "Jhargram",
  "Shirpur-Warwade",
  "Tilhar",
  "Sindhnur",
  "Udumalaipettai",
  "Malkapur",
  "Wanaparthy",
  "Gudur",
  "Kendujhar",
  "Mandla",
  "Mandi",
  "Nedumangad",
  "North Lakhimpur",
  "Vinukonda",
  "Tiptur",
  "Gobichettipalayam",
  "Sunabeda",
  "Wani",
  "Upleta",
  "Narasapuram",
  "Nuzvid",
  "Tezpur",
  "Una",
  "Markapur",
  "Sheopur",
  "Thiruvarur",
  "Sidhpur",
  "Sahaswan",
  "Suratgarh",
  "Shajapur",
  "Rayagada",
  "Lonavla",
  "Ponnur",
  "Kagaznagar",
  "Gadwal",
  "Bhatapara",
  "Kandukur",
  "Sangareddy",
  "Unjha",
  "Lunglei",
  "Karimganj",
  "Kannur",
  "Bobbili",
  "Mokameh",
  "Talegaon Dabhade",
  "Anjangaon",
  "Mangrol",
  "Sunam",
  "Gangarampur",
  "Thiruvallur",
  "Tirur",
  "Rath",
  "Jatani",
  "Viramgam",
  "Rajsamand",
  "Yanam",
  "Kottayam",
  "Panruti",
  "Dhuri",
  "Namakkal",
  "Kasaragod",
  "Modasa",
  "Rayadurg",
  "Supaul",
  "Kunnamkulam",
  "Umred",
  "Bellampalle",
  "Sibsagar",
  "Mandi Dabwali",
  "Ottappalam",
  "Dumraon",
  "Samalkot",
  "Jaggaiahpet",
  "Goalpara",
  "Tuni",
  "Lachhmangarh",
  "Bhongir",
  "Amalapuram",
  "Firozpur Cantt.",
  "Vikarabad",
  "Thiruvalla",
  "Sherkot",
  "Palghar",
  "Shegaon",
  "Jangaon",
  "Bheemunipatnam",
  "Panna",
  "Thodupuzha",
  "KathUrban Agglomeration",
  "Palitana",
  "Arwal",
  "Venkatagiri",
  "Kalpi",
  "Rajgarh (Churu)",
  "Sattenapalle",
  "Arsikere",
  "Ozar",
  "Thirumangalam",
  "Petlad",
  "Nasirabad",
  "Phaltan",
  "Rampurhat",
  "Nanjangud",
  "Forbesganj",
  "Tundla",
  "BhabUrban Agglomeration",
  "Sagara",
  "Pithapuram",
  "Sira",
  "Bhadrachalam",
  "Charkhi Dadri",
  "Chatra",
  "Palasa Kasibugga",
  "Nohar",
  "Yevla",
  "Sirhind Fatehgarh Sahib",
  "Bhainsa",
  "Parvathipuram",
  "Shahade",
  "Chalakudy",
  "Narkatiaganj",
  "Kapadvanj",
  "Macherla",
  "Raghogarh-Vijaypur",
  "Rupnagar",
  "Naugachhia",
  "Sendhwa",
  "Byasanagar",
  "Sandila",
  "Gooty",
  "Salur",
  "Nanpara",
  "Sardhana",
  "Vita",
  "Gumia",
  "Puttur",
  "Jalandhar Cantt.",
  "Nehtaur",
  "Changanassery",
  "Mandapeta",
  "Dumka",
  "Seohara",
  "Umarkhed",
  "Madhupur",
  "Vikramasingapuram",
  "Punalur",
  "Kendrapara",
  "Sihor",
  "Nellikuppam",
  "Samana",
  "Warora",
  "Nilambur",
  "Rasipuram",
  "Ramnagar",
  "Jammalamadugu",
  "Nawanshahr",
  "Thoubal",
  "Athni",
  "Cherthala",
  "Sidhi",
  "Farooqnagar",
  "Peddapuram",
  "Chirkunda",
  "Pachora",
  "Madhepura",
  "Pithoragarh",
  "Tumsar",
  "Phalodi",
  "Tiruttani",
  "Rampura Phul",
  "Perinthalmanna",
  "Padrauna",
  "Pipariya",
  "Dalli-Rajhara",
  "Punganur",
  "Mattannur",
  "Mathura",
  "Thakurdwara",
  "Nandivaram-Guduvancheri",
  "Mulbagal",
  "Manjlegaon",
  "Wankaner",
  "Sillod",
  "Nidadavole",
  "Surapura",
  "Rajagangapur",
  "Sheikhpura",
  "Parlakhemundi",
  "Kalimpong",
  "Siruguppa",
  "Arvi",
  "Limbdi",
  "Barpeta",
  "Manglaur",
  "Repalle",
  "Mudhol",
  "Shujalpur",
  "Mandvi",
  "Thangadh",
  "Sironj",
  "Nandura",
  "Shoranur",
  "Nathdwara",
  "Periyakulam",
  "Sultanganj",
  "Medak",
  "Narayanpet",
  "Raxaul Bazar",
  "Rajauri",
  "Pernampattu",
  "Nainital",
  "Ramachandrapuram",
  "Vaijapur",
  "Nangal",
  "Sidlaghatta",
  "Punch",
  "Pandhurna",
  "Wadgaon Road",
  "Talcher",
  "Varkala",
  "Pilani",
  "Nowgong",
  "Naila Janjgir",
  "Mapusa",
  "Vellakoil",
  "Merta City",
  "Sivaganga",
  "Mandideep",
  "Sailu",
  "Vyara",
  "Kovvur",
  "Vadalur",
  "Nawabganj",
  "Padra",
  "Sainthia",
  "Siana",
  "Shahpur",
  "Sojat",
  "Noorpur",
  "Paravoor",
  "Murtijapur",
  "Ramnagar",
  "Sundargarh",
  "Taki",
  "Saundatti-Yellamma",
  "Pathanamthitta",
  "Wadi",
  "Rameshwaram",
  "Tasgaon",
  "Sikandra Rao",
  "Sihora",
  "Tiruvethipuram",
  "Tiruvuru",
  "Mehkar",
  "Peringathur",
  "Perambalur",
  "Manvi",
  "Zunheboto",
  "Mahnar Bazar",
  "Attingal",
  "Shahbad",
  "Puranpur",
  "Nelamangala",
  "Nakodar",
  "Lunawada",
  "Murshidabad",
  "Mahe",
  "Lanka",
  "Rudauli",
  "Tuensang",
  "Lakshmeshwar",
  "Zira",
  "Yawal",
  "Thana Bhawan",
  "Ramdurg",
  "Pulgaon",
  "Sadasivpet",
  "Nargund",
  "Neem-Ka-Thana",
  "Memari",
  "Nilanga",
  "Naharlagun",
  "Pakaur",
  "Wai",
  "Tarikere",
  "Malavalli",
  "Raisen",
  "Lahar",
  "Uravakonda",
  "Savanur",
  "Sirohi",
  "Udhampur",
  "Umarga",
  "Pratapgarh",
  "Lingsugur",
  "Usilampatti",
  "Palia Kalan",
  "Wokha",
  "Rajpipla",
  "Vijayapura",
  "Rawatbhata",
  "Sangaria",
  "Paithan",
  "Rahuri",
  "Patti",
  "Zaidpur",
  "Lalsot",
  "Maihar",
  "Vedaranyam",
  "Nawapur",
  "Solan",
  "Vapi",
  "Sanawad",
  "Warisaliganj",
  "Revelganj",
  "Sabalgarh",
  "Tuljapur",
  "Simdega",
  "Musabani",
  "Kodungallur",
  "Phulabani",
  "Umreth",
  "Narsipatnam",
  "Nautanwa",
  "Rajgir",
  "Yellandu",
  "Sathyamangalam",
  "Pilibanga",
  "Morshi",
  "Pehowa",
  "Sonepur",
  "Pappinisseri",
  "Zamania",
  "Mihijam",
  "Purna",
  "Puliyankudi",
  "Shikarpur, Bulandshahr",
  "Umaria",
  "Porsa",
  "Naugawan Sadat",
  "Fatehpur Sikri",
  "Manuguru",
  "Udaipur",
  "Pipar City",
  "Pattamundai",
  "Nanjikottai",
  "Taranagar",
  "Yerraguntla",
  "Satana",
  "Sherghati",
  "Sankeshwara",
  "Madikeri",
  "Thuraiyur",
  "Sanand",
  "Rajula",
  "Kyathampalle",
  "Shahabad, Rampur",
  "Tilda Newra",
  "Narsinghgarh",
  "Chittur-Thathamangalam",
  "Malaj Khand",
  "Sarangpur",
  "Robertsganj",
  "Sirkali",
  "Radhanpur",
  "Tiruchendur",
  "Utraula",
  "Patratu",
  "Vijainagar, Ajmer",
  "Periyasemur",
  "Pathri",
  "Sadabad",
  "Talikota",
  "Sinnar",
  "Mungeli",
  "Sedam",
  "Shikaripur",
  "Sumerpur",
  "Sattur",
  "Sugauli",
  "Lumding",
  "Vandavasi",
  "Titlagarh",
  "Uchgaon",
  "Mokokchung",
  "Paschim Punropara",
  "Sagwara",
  "Ramganj Mandi",
  "Tarakeswar",
  "Mahalingapura",
  "Dharmanagar",
  "Mahemdabad",
  "Manendragarh",
  "Uran",
  "Tharamangalam",
  "Tirukkoyilur",
  "Pen",
  "Makhdumpur",
  "Maner",
  "Oddanchatram",
  "Palladam",
  "Mundi",
  "Nabarangapur",
  "Mudalagi",
  "Samalkha",
  "Nepanagar",
  "Karjat",
  "Ranavav",
  "Pedana",
  "Pinjore",
  "Lakheri",
  "Pasan",
  "Puttur",
  "Vadakkuvalliyur",
  "Tirukalukundram",
  "Mahidpur",
  "Mussoorie",
  "Muvattupuzha",
  "Rasra",
  "Udaipurwati",
  "Manwath",
  "Adoor",
  "Uthamapalayam",
  "Partur",
  "Nahan",
  "Ladwa",
  "Mankachar",
  "Nongstoin",
  "Losal",
  "Sri Madhopur",
  "Ramngarh",
  "Mavelikkara",
  "Rawatsar",
  "Rajakhera",
  "Lar",
  "Lal Gopalganj Nindaura",
  "Muddebihal",
  "Sirsaganj",
  "Shahpura",
  "Surandai",
  "Sangole",
  "Pavagada",
  "Tharad",
  "Mansa",
  "Umbergaon",
  "Mavoor",
  "Nalbari",
  "Talaja",
  "Malur",
  "Mangrulpir",
  "Soro",
  "Shahpura",
  "Vadnagar",
  "Raisinghnagar",
  "Sindhagi",
  "Sanduru",
  "Sohna",
  "Manavadar",
  "Pihani",
  "Safidon",
  "Risod",
  "Rosera",
  "Sankari",
  "Malpura",
  "Sonamukhi",
  "Shamsabad, Agra",
  "Nokha",
  "PandUrban Agglomeration",
  "Mainaguri",
  "Afzalpur",
  "Shirur",
  "Salaya",
  "Shenkottai",
  "Pratapgarh",
  "Vadipatti",
  "Nagarkurnool",
  "Savner",
  "Sasvad",
  "Rudrapur",
  "Soron",
  "Sholingur",
  "Pandharkaoda",
  "Perumbavoor",
  "Maddur",
  "Nadbai",
  "Talode",
  "Shrigonda",
  "Madhugiri",
  "Tekkalakote",
  "Seoni-Malwa",
  "Shirdi",
  "SUrban Agglomerationr",
  "Terdal",
  "Raver",
  "Tirupathur",
  "Taraori",
  "Mukhed",
  "Manachanallur",
  "Rehli",
  "Sanchore",
  "Rajura",
  "Piro",
  "Mudabidri",
  "Vadgaon Kasba",
  "Nagar",
  "Vijapur",
  "Viswanatham",
  "Polur",
  "Panagudi",
  "Manawar",
  "Tehri",
  "Samdhan",
  "Pardi",
  "Rahatgarh",
  "Panagar",
  "Uthiramerur",
  "Tirora",
  "Rangia",
  "Sahjanwa",
  "Wara Seoni",
  "Magadi",
  "Rajgarh (Alwar)",
  "Rafiganj",
  "Tarana",
  "Rampur Maniharan",
  "Sheoganj",
  "Raikot",
  "Pauri",
  "Sumerpur",
  "Navalgund",
  "Shahganj",
  "Marhaura",
  "Tulsipur",
  "Sadri",
  "Thiruthuraipoondi",
  "Shiggaon",
  "Pallapatti",
  "Mahendragarh",
  "Sausar",
  "Ponneri",
  "Mahad",
  "Lohardaga",
  "Tirwaganj",
  "Margherita",
  "Sundarnagar",
  "Rajgarh",
  "Mangaldoi",
  "Renigunta",
  "Longowal",
  "Ratia",
  "Lalgudi",
  "Shrirangapattana",
  "Niwari",
  "Natham",
  "Unnamalaikadai",
  "PurqUrban Agglomerationzi",
  "Shamsabad, Farrukhabad",
  "Mirganj",
  "Todaraisingh",
  "Warhapur",
  "Rajam",
  "Urmar Tanda",
  "Lonar",
  "Powayan",
  "P.N.Patti",
  "Palampur",
  "Srisailam Project (Right Flank Colony) Township",
  "Sindagi",
  "Sandi",
  "Vaikom",
  "Malda",
  "Tharangambadi",
  "Sakaleshapura",
  "Lalganj",
  "Malkangiri",
  "Rapar",
  "Mauganj",
  "Todabhim",
  "Srinivaspur",
  "Murliganj",
  "Reengus",
  "Sawantwadi",
  "Tittakudi",
  "Lilong",
  "Rajaldesar",
  "Pathardi",
  "Achhnera",
  "Pacode",
  "Naraura",
  "Nakur",
  "Palai",
  "Morinda, India",
  "Manasa",
  "Nainpur",
  "Sahaspur",
  "Pauni",
  "Prithvipur",
  "Ramtek",
  "Silapathar",
  "Songadh",
  "Safipur",
  "Sohagpur",
  "Mul",
  "Sadulshahar",
  "Phillaur",
  "Sambhar",
  "Prantij",
  "Nagla",
  "Pattran",
  "Mount Abu",
  "Reoti",
  "Tenu dam-cum-Kathhara",
  "Panchla",
  "Sitarganj",
  "Pasighat",
  "Motipur",
  "O' Valley",
  "Raghunathpur",
  "Suriyampalayam",
  "Qadian",
  "Rairangpur",
  "Silvassa",
  "Nowrozabad (Khodargama)",
  "Mangrol",
  "Soyagaon",
  "Sujanpur",
  "Manihari",
  "Sikanderpur",
  "Mangalvedhe",
  "Phulera",
  "Ron",
  "Sholavandan",
  "Saidpur",
  "Shamgarh",
  "Thammampatti",
  "Maharajpur",
  "Multai",
  "Mukerian",
  "Sirsi",
  "Purwa",
  "Sheohar",
  "Namagiripettai",
  "Parasi",
  "Lathi",
  "Lalganj",
  "Narkhed",
  "Mathabhanga",
  "Shendurjana",
  "Peravurani",
  "Mariani",
  "Phulpur",
  "Rania",
  "Pali",
  "Pachore",
  "Parangipettai",
  "Pudupattinam",
  "Panniyannur",
  "Maharajganj",
  "Rau",
  "Monoharpur",
  "Mandawa",
  "Marigaon",
  "Pallikonda",
  "Pindwara",
  "Shishgarh",
  "Patur",
  "Mayang Imphal",
  "Mhowgaon",
  "Guruvayoor",
  "Mhaswad",
  "Sahawar",
  "Sivagiri",
  "Mundargi",
  "Punjaipugalur",
  "Kailasahar",
  "Samthar",
  "Sakti",
  "Sadalagi",
  "Silao",
  "Mandalgarh",
  "Loha",
  "Pukhrayan",
  "Padmanabhapuram",
  "Belonia",
  "Saiha",
  "Srirampore",
  "Talwara",
  "Puthuppally",
  "Khowai",
  "Vijaypur",
  "Takhatgarh",
  "Thirupuvanam",
  "Adra",
  "Piriyapatna",
  "Obra",
  "Adalaj",
  "Nandgaon",
  "Barh",
  "Chhapra",
  "Panamattom",
  "Niwai",
  "Bageshwar",
  "Tarbha",
  "Adyar",
  "Narsinghgarh",
  "Warud",
  "Asarganj",
  "Sarsod",
  "Gandhinagar",
  "Kullu",
  "Manali",
  "Mirzapur",
  "Kota",
  "Dispur",
  "Maharashtra",
  "Delhi",
  "Karnataka",
  "Gujarat",
  "Telangana",
  "Tamil Nadu",
  "West Bengal",
  "Maharashtra",
  "Rajasthan",
  "Gujarat",
  "Uttar Pradesh",
  "Uttar Pradesh",
  "Maharashtra",
  "Bihar",
  "Madhya Pradesh",
  "Maharashtra",
  "Madhya Pradesh",
  "Andhra Pradesh",
  "Gujarat",
  "Uttar Pradesh",
  "Punjab",
  "Gujarat",
  "Uttar Pradesh",
  "West Bengal",
  "Maharashtra",
  "Haryana",
  "Punjab",
  "Uttar Pradesh",
  "Maharashtra",
  "Maharashtra",
  "Uttar Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Rajasthan",
  "Punjab",
  "Chhattisgarh",
  "Uttar Pradesh",
  "Tamil Nadu",
  "Madhya Pradesh",
  "Madhya Pradesh",
  "Andhra Pradesh",
  "Tamil Nadu",
  "Assam",
  "Chandigarh",
  "Karnataka",
  "Uttar Pradesh",
  "Uttar Pradesh",
  "Haryana",
  "Uttar Pradesh",
  "Maharashtra",
  "Jharkhand",
  "Punjab",
  "Tamil Nadu",
  "Odisha",
  "Tamil Nadu",
  "Telangana",
  "Maharashtra",
  "Kerala",
  "Maharashtra",
  "Uttar Pradesh",
  "Andhra Pradesh",
  "Maharashtra",
  "Rajasthan",
  "Uttar Pradesh",
  "Jharkhand",
  "Chhattisgarh",
  "Odisha",
  "Kerala",
  "Rajasthan",
  "Gujarat",
  "Uttarakhand",
  "West Bengal",
  "Maharashtra",
  "Rajasthan",
  "Gujarat",
  "Madhya Pradesh",
  "Maharashtra",
  "Uttar Pradesh",
  "Uttar Pradesh",
  "Puducherry",
  "Andhra Pradesh",
  "Jammu and Kashmir",
  "Karnataka",
  "Odisha",
  "Karnataka",
  "Tamil Nadu",
  "Maharashtra",
  "Bihar",
  "Tamil Nadu",
  "Karnataka",
  "Kerala",
  "Maharashtra",
  "Andhra Pradesh",
  "Jharkhand",
  "Andhra Pradesh",
  "Karnataka",
  "Tripura",
  "Bihar",
  "Maharashtra",
  "Maharashtra",
  "Chhattisgarh",
  "Rajasthan",
  "Odisha",
  "Karnataka",
  "Bihar",
  "Maharashtra",
  "Kerala",
  "West Bengal",
  "Chhattisgarh",
  "Uttar Pradesh",
  "Kerala",
  "Rajasthan",
  "Andhra Pradesh",
  "Telangana",
  "Madhya Pradesh",
  "Karnataka",
  "Haryana",
  "Haryana",
  "Haryana",
  "Bihar",
  "West Bengal",
  "Mizoram",
  "Maharashtra",
  "Andhra Pradesh",
  "Haryana",
  "Punjab",
  "Uttar Pradesh",
  "Karnataka",
  "Madhya Pradesh",
  "Uttar Pradesh",
  "Chhattisgarh",
  "Meghalaya",
  "Manipur",
  "Uttar Pradesh",
  "Tamil Nadu",
  "Andhra Pradesh",
  "Bihar",
  "Telangana",
  "Maharashtra",
  "Uttar Pradesh",
  "Rajasthan",
  "Bihar",
  "Delhi",
  "Bihar",
  "Andhra Pradesh",
  "Telangana",
  "Rajasthan",
  "Madhya Pradesh",
  "Andhra Pradesh",
  "Bihar",
  "Uttarakhand",
  "Haryana",
  "Tamil Nadu",
  "Tamil Nadu",
  "Madhya Pradesh",
  "West Bengal",
  "Uttar Pradesh",
  "Gujarat",
  "Haryana",
  "West Bengal",
  "Andhra Pradesh",
  "Bihar",
  "Haryana",
  "Karnataka",
  "Maharashtra",
  "Jharkhand",
  "Andhra Pradesh",
  "Andhra Pradesh",
  "Madhya Pradesh",
  "Haryana",
  "Gujarat",
  "Kerala",
  "Gujarat",
  "Bihar",
  "West Bengal",
  "Rajasthan",
  "Gujarat",
  "Uttar Pradesh",
  "Uttar Pradesh",
  "Rajasthan",
  "Tamil Nadu",
  "Madhya Pradesh",
  "Telangana",
  "Gujarat",
  "Assam",
  "Odisha",
  "Madhya Pradesh",
  "Uttar Pradesh",
  "West Bengal",
  "West Bengal",
  "Jharkhand",
  "Jharkhand",
  "Kerala",
  "Haryana",
  "Andhra Pradesh",
  "Uttar Pradesh",
  "West Bengal",
  "Gujarat",
  "Punjab",
  "Punjab",
  "Jammu and Kashmir",
  "Andhra Pradesh",
  "Haryana",
  "Rajasthan",
  "Andhra Pradesh",
  "Tamil Nadu",
  "Gujarat",
  "Haryana",
  "Gujarat",
  "Telangana",
  "Odisha",
  "Karnataka",
  "Tamil Nadu",
  "Punjab",
  "Uttarakhand",
  "Madhya Pradesh",
  "Bihar",
  "Haryana",
  "Andhra Pradesh",
  "Gujarat",
  "Uttar Pradesh",
  "Uttar Pradesh",
  "Andhra Pradesh",
  "West Bengal",
  "West Bengal",
  "Madhya Pradesh",
  "Punjab",
  "Andhra Pradesh",
  "Uttarakhand",
  "West Bengal",
  "West Bengal",
  "Bihar",
  "Bihar",
  "Gujarat",
  "Madhya Pradesh",
  "West Bengal",
  "Himachal Pradesh",
  "Tamil Nadu",
  "Haryana",
  "Chhattisgarh",
  "Gujarat",
  "Jharkhand",
  "Andhra Pradesh",
  "Madhya Pradesh",
  "Assam",
  "Karnataka",
  "West Bengal",
  "Karnataka",
  "Bihar",
  "Andhra Pradesh",
  "Punjab",
  "Uttar Pradesh",
  "Bihar",
  "Tamil Nadu",
  "Punjab",
  "Madhya Pradesh",
  "Haryana",
  "Gujarat",
  "Andhra Pradesh",
  "West Bengal",
  "Karnataka",
  "Chhattisgarh",
  "Bihar",
  "Uttar Pradesh",
  "Nagaland",
  "Punjab",
  "Rajasthan",
  "Tamil Nadu",
  "Andhra Pradesh",
  "Uttarakhand",
  "Tamil Nadu",
  "West Bengal",
  "Karnataka",
  "Andhra Pradesh",
  "Odisha",
  "Telangana",
  "Andhra Pradesh",
  "Telangana",
  "Maharashtra",
  "Punjab",
  "Assam",
  "Andhra Pradesh",
  "Chhattisgarh",
  "Uttarakhand",
  "Gujarat",
  "Chhattisgarh",
  "Jharkhand",
  "Uttar Pradesh",
  "West Bengal",
  "Gujarat",
  "Bihar",
  "Uttar Pradesh",
  "Maharashtra",
  "Maharashtra",
  "Gujarat",
  "Maharashtra",
  "Uttar Pradesh",
  "Jharkhand",
  "Punjab",
  "Odisha",
  "Karnataka",
  "Bihar",
  "Andhra Pradesh",
  "Tamil Nadu",
  "Jammu and Kashmir",
  "Andhra Pradesh",
  "Maharashtra",
  "Odisha",
  "Bihar",
  "Telangana",
  "Maharashtra",
  "Karnataka",
  "Gujarat",
  "Tamil Nadu",
  "Bihar",
  "Goa",
  "Maharashtra",
  "Andhra Pradesh",
  "Tamil Nadu",
  "Bihar",
  "Maharashtra",
  "Bihar",
  "Punjab",
  "Uttar Pradesh",
  "Rajasthan",
  "Punjab",
  "Andhra Pradesh",
  "Bihar",
  "Kerala",
  "Haryana",
  "Rajasthan",
  "Uttar Pradesh",
  "Madhya Pradesh",
  "Andaman and Nicobar Islands",
  "Bihar",
  "Goa",
  "Assam",
  "Madhya Pradesh",
  "Nagaland",
  "Odisha",
  "Bihar",
  "Odisha",
  "Telangana",
  "Tamil Nadu",
  "Maharashtra",
  "Punjab",
  "Uttar Pradesh",
  "Tamil Nadu",
  "Uttar Pradesh",
  "Andhra Pradesh",
  "Tamil Nadu",
  "Madhya Pradesh",
  "Tamil Nadu",
  "Goa",
  "Maharashtra",
  "Madhya Pradesh",
  "Madhya Pradesh",
  "Punjab",
  "Rajasthan",
  "Maharashtra",
  "Telangana",
  "Uttar Pradesh",
  "Madhya Pradesh",
  "Karnataka",
  "Andhra Pradesh",
  "Maharashtra",
  "Uttarakhand",
  "Maharashtra",
  "Uttar Pradesh",
  "Telangana",
  "Tamil Nadu",
  "Uttar Pradesh",
  "Jharkhand",
  "Tamil Nadu",
  "Kerala",
  "Bihar",
  "Bihar",
  "Andhra Pradesh",
  "Gujarat",
  "Puducherry",
  "Haryana",
  "Andhra Pradesh",
  "Chhattisgarh",
  "Punjab",
  "Jharkhand",
  "Gujarat",
  "Tamil Nadu",
  "Madhya Pradesh",
  "Rajasthan",
  "Gujarat",
  "Punjab",
  "Punjab",
  "Andhra Pradesh",
  "Chhattisgarh",
  "Madhya Pradesh",
  "Rajasthan",
  "Gujarat",
  "Odisha",
  "Telangana",
  "Jharkhand",
  "Telangana",
  "Karnataka",
  "Karnataka",
  "Madhya Pradesh",
  "Bihar",
  "Uttarakhand",
  "Madhya Pradesh",
  "Jharkhand",
  "Tamil Nadu",
  "Maharashtra",
  "Punjab",
  "Telangana",
  "Punjab",
  "Andhra Pradesh",
  "Gujarat",
  "Andhra Pradesh",
  "Gujarat",
  "Punjab",
  "Kerala",
  "Meghalaya",
  "Haryana",
  "Punjab",
  "Karnataka",
  "Maharashtra",
  "Gujarat",
  "Gujarat",
  "Odisha",
  "Tamil Nadu",
  "Kerala",
  "Gujarat",
  "Tamil Nadu",
  "Punjab",
  "Tamil Nadu",
  "Punjab",
  "Kerala",
  "Maharashtra",
  "Andhra Pradesh",
  "Andhra Pradesh",
  "Tamil Nadu",
  "Kerala",
  "Assam",
  "Tamil Nadu",
  "Tamil Nadu",
  "Andhra Pradesh",
  "Kerala",
  "Andhra Pradesh",
  "Haryana",
  "Punjab",
  "Tamil Nadu",
  "Tamil Nadu",
  "Maharashtra",
  "Karnataka",
  "Uttar Pradesh",
  "Jharkhand",
  "Chhattisgarh",
  "Telangana",
  "Odisha",
  "Kerala",
  "Madhya Pradesh",
  "Punjab",
  "Uttar Pradesh",
  "Odisha",
  "Maharashtra",
  "Bihar",
  "Assam",
  "Tamil Nadu",
  "Maharashtra",
  "Jammu and Kashmir",
  "Uttar Pradesh",
  "Punjab",
  "Uttar Pradesh",
  "Telangana",
  "Karnataka",
  "Odisha",
  "Telangana",
  "Bihar",
  "West Bengal",
  "Haryana",
  "Rajasthan",
  "Tamil Nadu",
  "Karnataka",
  "Telangana",
  "West Bengal",
  "Punjab",
  "West Bengal",
  "Madhya Pradesh",
  "Telangana",
  "Andhra Pradesh",
  "Tamil Nadu",
  "Haryana",
  "Rajasthan",
  "Assam",
  "Bihar",
  "Gujarat",
  "Uttar Pradesh",
  "Rajasthan",
  "Andhra Pradesh",
  "Haryana",
  "Tamil Nadu",
  "Uttar Pradesh",
  "Bihar",
  "Uttar Pradesh",
  "Maharashtra",
  "Rajasthan",
  "Telangana",
  "West Bengal",
  "Assam",
  "West Bengal",
  "Maharashtra",
  "Uttar Pradesh",
  "Karnataka",
  "Tamil Nadu",
  "Maharashtra",
  "Telangana",
  "Andhra Pradesh",
  "Odisha",
  "Madhya Pradesh",
  "Himachal Pradesh",
  "Kerala",
  "Assam",
  "Andhra Pradesh",
  "Karnataka",
  "Tamil Nadu",
  "Odisha",
  "Maharashtra",
  "Gujarat",
  "Andhra Pradesh",
  "Andhra Pradesh",
  "Assam",
  "Gujarat",
  "Andhra Pradesh",
  "Madhya Pradesh",
  "Tamil Nadu",
  "Gujarat",
  "Uttar Pradesh",
  "Rajasthan",
  "Madhya Pradesh",
  "Odisha",
  "Maharashtra",
  "Andhra Pradesh",
  "Telangana",
  "Telangana",
  "Chhattisgarh",
  "Andhra Pradesh",
  "Telangana",
  "Gujarat",
  "Mizoram",
  "Assam",
  "Kerala",
  "Andhra Pradesh",
  "Bihar",
  "Maharashtra",
  "Maharashtra",
  "Gujarat",
  "Punjab",
  "West Bengal",
  "Tamil Nadu",
  "Kerala",
  "Uttar Pradesh",
  "Odisha",
  "Gujarat",
  "Rajasthan",
  "Puducherry",
  "Kerala",
  "Tamil Nadu",
  "Punjab",
  "Tamil Nadu",
  "Kerala",
  "Gujarat",
  "Andhra Pradesh",
  "Bihar",
  "Kerala",
  "Maharashtra",
  "Telangana",
  "Assam",
  "Haryana",
  "Kerala",
  "Bihar",
  "Andhra Pradesh",
  "Andhra Pradesh",
  "Assam",
  "Andhra Pradesh",
  "Rajasthan",
  "Telangana",
  "Andhra Pradesh",
  "Punjab",
  "Telangana",
  "Kerala",
  "Uttar Pradesh",
  "Maharashtra",
  "Maharashtra",
  "Telangana",
  "Andhra Pradesh",
  "Madhya Pradesh",
  "Kerala",
  "Jammu and Kashmir",
  "Gujarat",
  "Bihar",
  "Andhra Pradesh",
  "Uttar Pradesh",
  "Rajasthan",
  "Andhra Pradesh",
  "Karnataka",
  "Maharashtra",
  "Tamil Nadu",
  "Gujarat",
  "Rajasthan",
  "Maharashtra",
  "West Bengal",
  "Karnataka",
  "Bihar",
  "Uttar Pradesh",
  "Bihar",
  "Karnataka",
  "Andhra Pradesh",
  "Karnataka",
  "Telangana",
  "Haryana",
  "Jharkhand",
  "Andhra Pradesh",
  "Rajasthan",
  "Maharashtra",
  "Punjab",
  "Telangana",
  "Andhra Pradesh",
  "Maharashtra",
  "Kerala",
  "Bihar",
  "Gujarat",
  "Andhra Pradesh",
  "Madhya Pradesh",
  "Punjab",
  "Bihar",
  "Madhya Pradesh",
  "Odisha",
  "Uttar Pradesh",
  "Andhra Pradesh",
  "Andhra Pradesh",
  "Uttar Pradesh",
  "Uttar Pradesh",
  "Maharashtra",
  "Jharkhand",
  "Karnataka",
  "Punjab",
  "Uttar Pradesh",
  "Kerala",
  "Andhra Pradesh",
  "Jharkhand",
  "Uttar Pradesh",
  "Maharashtra",
  "Jharkhand",
  "Tamil Nadu",
  "Kerala",
  "Odisha",
  "Gujarat",
  "Tamil Nadu",
  "Punjab",
  "Maharashtra",
  "Kerala",
  "Tamil Nadu",
  "Uttarakhand",
  "Andhra Pradesh",
  "Punjab",
  "Manipur",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Telangana",
  "Andhra Pradesh",
  "Jharkhand",
  "Maharashtra",
  "Bihar",
  "Uttarakhand",
  "Maharashtra",
  "Rajasthan",
  "Tamil Nadu",
  "Punjab",
  "Kerala",
  "Uttar Pradesh",
  "Madhya Pradesh",
  "Chhattisgarh",
  "Andhra Pradesh",
  "Kerala",
  "Uttar Pradesh",
  "Uttar Pradesh",
  "Tamil Nadu",
  "Karnataka",
  "Maharashtra",
  "Gujarat",
  "Maharashtra",
  "Andhra Pradesh",
  "Karnataka",
  "Odisha",
  "Bihar",
  "Odisha",
  "West Bengal",
  "Karnataka",
  "Maharashtra",
  "Gujarat",
  "Assam",
  "Uttarakhand",
  "Andhra Pradesh",
  "Karnataka",
  "Madhya Pradesh",
  "Gujarat",
  "Gujarat",
  "Madhya Pradesh",
  "Maharashtra",
  "Kerala",
  "Rajasthan",
  "Tamil Nadu",
  "Bihar",
  "Telangana",
  "Telangana",
  "Bihar",
  "Jammu and Kashmir",
  "Tamil Nadu",
  "Uttarakhand",
  "Andhra Pradesh",
  "Maharashtra",
  "Punjab",
  "Karnataka",
  "Jammu and Kashmir",
  "Madhya Pradesh",
  "Maharashtra",
  "Odisha",
  "Kerala",
  "Rajasthan",
  "Madhya Pradesh",
  "Chhattisgarh",
  "Goa",
  "Tamil Nadu",
  "Rajasthan",
  "Tamil Nadu",
  "Madhya Pradesh",
  "Maharashtra",
  "Gujarat",
  "Andhra Pradesh",
  "Tamil Nadu",
  "Uttar Pradesh",
  "Gujarat",
  "West Bengal",
  "Uttar Pradesh",
  "Karnataka",
  "Rajasthan",
  "Uttar Pradesh",
  "Kerala",
  "Maharashtra",
  "Bihar",
  "Odisha",
  "West Bengal",
  "Karnataka",
  "Kerala",
  "Karnataka",
  "Tamil Nadu",
  "Maharashtra",
  "Uttar Pradesh",
  "Madhya Pradesh",
  "Tamil Nadu",
  "Andhra Pradesh",
  "Maharashtra",
  "Kerala",
  "Tamil Nadu",
  "Karnataka",
  "Nagaland",
  "Bihar",
  "Kerala",
  "Haryana",
  "Uttar Pradesh",
  "Karnataka",
  "Punjab",
  "Gujarat",
  "West Bengal",
  "Puducherry",
  "Assam",
  "Uttar Pradesh",
  "Nagaland",
  "Karnataka",
  "Punjab",
  "Maharashtra",
  "Uttar Pradesh",
  "Karnataka",
  "Maharashtra",
  "Telangana",
  "Karnataka",
  "Rajasthan",
  "West Bengal",
  "Maharashtra",
  "Arunachal Pradesh",
  "Jharkhand",
  "Maharashtra",
  "Karnataka",
  "Karnataka",
  "Madhya Pradesh",
  "Madhya Pradesh",
  "Andhra Pradesh",
  "Karnataka",
  "Rajasthan",
  "Jammu and Kashmir",
  "Maharashtra",
  "Rajasthan",
  "Karnataka",
  "Tamil Nadu",
  "Uttar Pradesh",
  "Nagaland",
  "Gujarat",
  "Karnataka",
  "Rajasthan",
  "Rajasthan",
  "Maharashtra",
  "Maharashtra",
  "Punjab",
  "Uttar Pradesh",
  "Rajasthan",
  "Madhya Pradesh",
  "Tamil Nadu",
  "Maharashtra",
  "Himachal Pradesh",
  "Gujarat",
  "Madhya Pradesh",
  "Bihar",
  "Bihar",
  "Madhya Pradesh",
  "Maharashtra",
  "Jharkhand",
  "Jharkhand",
  "Kerala",
  "Odisha",
  "Gujarat",
  "Andhra Pradesh",
  "Uttar Pradesh",
  "Bihar",
  "Telangana",
  "Tamil Nadu",
  "Rajasthan",
  "Maharashtra",
  "Haryana",
  "Bihar",
  "Kerala",
  "Uttar Pradesh",
  "Jharkhand",
  "Maharashtra",
  "Tamil Nadu",
  "Uttar Pradesh",
  "Madhya Pradesh",
  "Madhya Pradesh",
  "Uttar Pradesh",
  "Uttar Pradesh",
  "Telangana",
  "Tripura",
  "Rajasthan",
  "Odisha",
  "Tamil Nadu",
  "Rajasthan",
  "Andhra Pradesh",
  "Maharashtra",
  "Bihar",
  "Karnataka",
  "Karnataka",
  "Tamil Nadu",
  "Gujarat",
  "Gujarat",
  "Telangana",
  "Uttar Pradesh",
  "Chhattisgarh",
  "Madhya Pradesh",
  "Kerala",
  "Madhya Pradesh",
  "Madhya Pradesh",
  "Uttar Pradesh",
  "Tamil Nadu",
  "Gujarat",
  "Tamil Nadu",
  "Uttar Pradesh",
  "Jharkhand",
  "Rajasthan",
  "Tamil Nadu",
  "Maharashtra",
  "Uttar Pradesh",
  "Karnataka",
  "Maharashtra",
  "Chhattisgarh",
  "Karnataka",
  "Karnataka",
  "Rajasthan",
  "Tamil Nadu",
  "Bihar",
  "Assam",
  "Tamil Nadu",
  "Odisha",
  "Maharashtra",
  "Nagaland",
  "West Bengal",
  "Rajasthan",
  "Rajasthan",
  "West Bengal",
  "Karnataka",
  "Tripura",
  "Gujarat",
  "Chhattisgarh",
  "Maharashtra",
  "Tamil Nadu",
  "Tamil Nadu",
  "Maharashtra",
  "Bihar",
  "Bihar",
  "Tamil Nadu",
  "Tamil Nadu",
  "Madhya Pradesh",
  "Odisha",
  "Karnataka",
  "Haryana",
  "Madhya Pradesh",
  "Maharashtra",
  "Gujarat",
  "Andhra Pradesh",
  "Haryana",
  "Rajasthan",
  "Madhya Pradesh",
  "Andhra Pradesh",
  "Tamil Nadu",
  "Tamil Nadu",
  "Madhya Pradesh",
  "Uttarakhand",
  "Kerala",
  "Uttar Pradesh",
  "Rajasthan",
  "Maharashtra",
  "Kerala",
  "Tamil Nadu",
  "Maharashtra",
  "Himachal Pradesh",
  "Haryana",
  "Assam",
  "Meghalaya",
  "Rajasthan",
  "Rajasthan",
  "Rajasthan",
  "Kerala",
  "Rajasthan",
  "Rajasthan",
  "Uttar Pradesh",
  "Uttar Pradesh",
  "Karnataka",
  "Uttar Pradesh",
  "Rajasthan",
  "Tamil Nadu",
  "Maharashtra",
  "Karnataka",
  "Gujarat",
  "Gujarat",
  "Gujarat",
  "Kerala",
  "Assam",
  "Gujarat",
  "Karnataka",
  "Maharashtra",
  "Odisha",
  "Rajasthan",
  "Gujarat",
  "Rajasthan",
  "Karnataka",
  "Karnataka",
  "Haryana",
  "Gujarat",
  "Uttar Pradesh",
  "Haryana",
  "Maharashtra",
  "Bihar",
  "Tamil Nadu",
  "Rajasthan",
  "West Bengal",
  "Uttar Pradesh",
  "Bihar",
  "West Bengal",
  "West Bengal",
  "Karnataka",
  "Maharashtra",
  "Gujarat",
  "Tamil Nadu",
  "Tripura",
  "Tamil Nadu",
  "Telangana",
  "Maharashtra",
  "Maharashtra",
  "Uttar Pradesh",
  "Uttar Pradesh",
  "Tamil Nadu",
  "Maharashtra",
  "Kerala",
  "Karnataka",
  "Rajasthan",
  "Maharashtra",
  "Maharashtra",
  "Karnataka",
  "Karnataka",
  "Madhya Pradesh",
  "Maharashtra",
  "Uttar Pradesh",
  "Karnataka",
  "Maharashtra",
  "Tamil Nadu",
  "Haryana",
  "Maharashtra",
  "Tamil Nadu",
  "Madhya Pradesh",
  "Rajasthan",
  "Maharashtra",
  "Bihar",
  "Karnataka",
  "Maharashtra",
  "Rajasthan",
  "Gujarat",
  "Tamil Nadu",
  "Tamil Nadu",
  "Tamil Nadu",
  "Madhya Pradesh",
  "Uttarakhand",
  "Uttar Pradesh",
  "Gujarat",
  "Madhya Pradesh",
  "Madhya Pradesh",
  "Tamil Nadu",
  "Maharashtra",
  "Assam",
  "Uttar Pradesh",
  "Madhya Pradesh",
  "Karnataka",
  "Rajasthan",
  "Bihar",
  "Madhya Pradesh",
  "Uttar Pradesh",
  "Rajasthan",
  "Punjab",
  "Uttarakhand",
  "Uttar Pradesh",
  "Karnataka",
  "Uttar Pradesh",
  "Bihar",
  "Uttar Pradesh",
  "Rajasthan",
  "Tamil Nadu",
  "Karnataka",
  "Tamil Nadu",
  "Haryana",
  "Madhya Pradesh",
  "Tamil Nadu",
  "Maharashtra",
  "Jharkhand",
  "Uttar Pradesh",
  "Assam",
  "Himachal Pradesh",
  "Madhya Pradesh",
  "Assam",
  "Andhra Pradesh",
  "Punjab",
  "Haryana",
  "Tamil Nadu",
  "Karnataka",
  "Madhya Pradesh",
  "Tamil Nadu",
  "Tamil Nadu",
  "Uttar Pradesh",
  "Uttar Pradesh",
  "Bihar",
  "Rajasthan",
  "Uttar Pradesh",
  "Andhra Pradesh",
  "Punjab",
  "Maharashtra",
  "Uttar Pradesh",
  "Tamil Nadu",
  "Himachal Pradesh",
  "Andhra Pradesh",
  "Karnataka",
  "Uttar Pradesh",
  "Kerala",
  "West Bengal",
  "Tamil Nadu",
  "Karnataka",
  "Bihar",
  "Odisha",
  "Gujarat",
  "Madhya Pradesh",
  "Rajasthan",
  "Karnataka",
  "Bihar",
  "Rajasthan",
  "Maharashtra",
  "Tamil Nadu",
  "Manipur",
  "Rajasthan",
  "Maharashtra",
  "Uttar Pradesh",
  "Tamil Nadu",
  "Uttar Pradesh",
  "Uttar Pradesh",
  "Kerala",
  "Punjab",
  "Madhya Pradesh",
  "Madhya Pradesh",
  "Uttar Pradesh",
  "Maharashtra",
  "Madhya Pradesh",
  "Maharashtra",
  "Assam",
  "Gujarat",
  "Uttar Pradesh",
  "Madhya Pradesh",
  "Maharashtra",
  "Rajasthan",
  "Punjab",
  "Rajasthan",
  "Rajasthan",
  "Uttarakhand",
  "Punjab",
  "Rajasthan",
  "Uttar Pradesh",
  "Jharkhand",
  "West Bengal",
  "Uttarakhand",
  "Arunachal Pradesh",
  "Bihar",
  "Tamil Nadu",
  "West Bengal",
  "Tamil Nadu",
  "Punjab",
  "Odisha",
  "Dadra and Nagar Haveli",
  "Madhya Pradesh",
  "Rajasthan",
  "Maharashtra",
  "Punjab",
  "Bihar",
  "Uttar Pradesh",
  "Maharashtra",
  "Rajasthan",
  "Karnataka",
  "Tamil Nadu",
  "Uttar Pradesh",
  "Madhya Pradesh",
  "Tamil Nadu",
  "Madhya Pradesh",
  "Madhya Pradesh",
  "Punjab",
  "Uttar Pradesh",
  "Uttar Pradesh",
  "Bihar",
  "Tamil Nadu",
  "Uttar Pradesh",
  "Gujarat",
  "Uttar Pradesh",
  "Maharashtra",
  "West Bengal",
  "Maharashtra",
  "Tamil Nadu",
  "Assam",
  "Uttar Pradesh",
  "Haryana",
  "Madhya Pradesh",
  "Madhya Pradesh",
  "Tamil Nadu",
  "Tamil Nadu",
  "Kerala",
  "Bihar",
  "Madhya Pradesh",
  "West Bengal",
  "Rajasthan",
  "Assam",
  "Tamil Nadu",
  "Rajasthan",
  "Uttar Pradesh",
  "Maharashtra",
  "Manipur",
  "Madhya Pradesh",
  "Kerala",
  "Maharashtra",
  "Uttar Pradesh",
  "Tamil Nadu",
  "Karnataka",
  "Tamil Nadu",
  "Tripura",
  "Uttar Pradesh",
  "Chhattisgarh",
  "Karnataka",
  "Bihar",
  "Rajasthan",
  "Maharashtra",
  "Uttar Pradesh",
  "Tamil Nadu",
  "Tripura",
  "Mizoram",
  "West Bengal",
  "Punjab",
  "Kerala",
  "Tripura",
  "Madhya Pradesh",
  "Rajasthan",
  "Tamil Nadu",
  "West Bengal",
  "Karnataka",
  "Uttar Pradesh",
  "Gujarat",
  "Maharashtra",
  "Bihar",
  "Gujarat",
  "Kerala",
  "Uttar Pradesh",
  "Uttarakhand",
  "Odisha",
  "Karnataka",
  "Madhya Pradesh",
  "Maharashtra",
  "Bihar",
  "Haryana",
  "Gujarat",
  "Himachal Pradesh",
  "Himachal Praddesh",
  "Uttar Pradesh",
  "Rajasthan",
  "Assam"
];

/*initiate the autocomplete function on the "myInput" element, and pass along the countries array as possible autocomplete values:*/
autocomplete(document.getElementById("myInput"), countries);
</script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>